version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      BACKEND_API_URL: http://backend:5000/api/data
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "80:80"

volumes:
  postgres_data:

networks:
  app-network:
