replicaCount: 1
image:
  repository: pranayv6664/flask-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "a86d3c494f3d6fd185017bf2d75621464adae708"
imageFrontend:
  repository: pranayv6664/flask-frontend
  pullPolicy: IfNotPresent
  tag: "43d051d84c48fbe57bb52917ee3eaeb22fc09b17"
service:
  type: ClusterIP
  port: 5000
serviceFrontend:
  type: NodePort
  port: 80
  nodePort: 30001
postgresql:
  auth:
    postgresPassword: "password"
    username: "postgres"
    password: "password"
    database: "mydb"
  primary:
    initdb:
      scripts:
        init.sql: |
          CREATE TABLE IF NOT EXISTS items (
            id SERIAL PRIMARY KEY,
            name TEXT NOT NULL,
            value INTEGER NOT NULL
          );
          INSERT INTO items (name, value) VALUES ('Item 1', 100);
          INSERT INTO items (name, value) VALUES ('Item 2', 200);
  service:
    port: 5432
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 8Gi
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
