apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.serviceFrontend.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceFrontend.port }}
      targetPort: 80
      nodePort: {{ .Values.serviceFrontend.nodePort }}
  selector:
    app: frontend
