name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: pranayv6664/flask-backend:${{ github.sha }}

      - name: Update Backend Image Tag in Helm Values YAML
        run: |
          yq eval '.image.tag = "${{ github.sha }}"' -i ../../charts/flask-kubernetes-app/values.yaml
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ../../charts/flask-kubernetes-app/values.yaml
          git commit -m "Update backend image tag to ${{ github.sha }}" || echo "No changes to commit"

      - name: Push changes to repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Build and Push Frontend Docker Images
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: pranayv6664/flask-frontend:${{ github.sha }}

      - name: Update Frontend image name in Helm Values yaml
        run: |
          yq eval '.imageFrontend.tag = "${{ github.sha }}"' -i ../../charts/flask-kubernetes-app/values.yaml
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ../../charts/flask-kubernetes-app/values.yaml
          git commit -m "Update frontend image tag to ${{ github.sha }}" || echo "No changes to commit"

      - name: Push changes to repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main

  package:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.10.0

      - name: Package Helm Chart
        run: |
          helm dependency update ../../charts/flask-kubernetes-app
          helm package ../../charts/flask-kubernetes-app --destination ../../charts

      - name: Upload Helm Charts Artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-charts
          path: ../../charts/*.tgz

      - name: Trigger Helm Github Repo Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: PranayV66/flask-kubernetes-app-helm
          event-type: publish-helm-charts
          client-payload: '{"ref": "main"}'


          


